name: BetterShulkerBoxes
author: Rektb
version: 2.14.1
description: Open your shulkerboxes easier!
main: me.rektb.bettershulkerboxes.BetterShulkerBoxes
api-version: 1.13
loadbefore: ["AutionHouse"]
softdepend: ["WorldGuard", "WorldEdit"]
commands:
  bsb:
    description: Main command for Better Shulker Boxes
    use: /bsb (subcommand)
permissions:
  bettershulkerboxes.*:
    description: Grants all BSB permissions
    children:
      bettershulkerboxes.use.*: true
      bettershulkerboxes.bypasscooldown: true
      bettershulkerboxes.updatenotify: true
      bettershulkerboxes.reload: true
  bettershulkerboxes.use.*:
    description: Allows you to open your shulkerbox by rightclicking it when holding it or inside an inventory
    children:
      bettershulkerboxes.use: true
      bettershulkerboxes.use.rightclick: true
  bettershulkerboxes.use:
    description: Allows the player to open shulkerboxes by rightclicking them while holding them in the hand
  bettershulkerboxes.use.rightclick:
    description: Allows the player to open shulkerboxes by rightclicking it inside an inventory
  bettershulkerboxes.bypasscooldown:
    description: Allows the player to bypass cooldown if enabled
  bettershulkerboxes.updatenotify:
    description: Allows the player to be notified of a new BSB version when you join, admin-only recommended.
  bettershulkerboxes.reload:
    description: Allows the player to reload the configuration file using /bsb reload
